<?php

declare(strict_types=1);

/**
 * @file
 * Functions to support theming in the Bootstrap Business theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function bootstrap_business_preprocess_html(array &$variables): void {
  $color_scheme_library = 'bootstrap_business/color-'.theme_get_setting('color_scheme');
  $variables['#attached']['library'][] = $color_scheme_library;
  $variables['attributes']['class'][] = 'mt-color-scheme-' . theme_get_setting('color_scheme');
}

function bootstrap_business_preprocess_node__card(array &$variables): void {
  $variables['#attached']['library'][] = 'bootstrap_business/node-view-mode-card';
}

/**
 * Implements hook_preprocess_node().
 */
function bootstrap_business_preprocess_node(array &$variables) {
  $variables['#attached']['library'][] = 'bootstrap_business/node';
}